### ISSUE TITLE
Unable to install Price Wise in Firefox Nightly (65.0a1)

### ISSUE THREAD

**Issue by vhfmag** [mozilla/price-wise#272] opened 2018-11-16 11:13 UTC
I can't install either Price Wise or Email Tabs, because "Price Wise requires Firefox 63 or later" even though I'm using Nightly (65.0a1, https://mybrowser.fyi/report/5beea4a4202b180014fc5474). Maybe it's intentional, maybe the issue is with Test Pilot, but I looked for similar issues and couldn't find, so I am creating this one.

A screenshot of the message:
![Screenshot of the message](https://user-images.githubusercontent.com/357835/48618005-e49eaf00-e98f-11e8-86e9-74824eb380fe.png)

**Comment by Softvision-RemusDranca** [comment] 2018-11-16 12:06
Hi , @vhfmag , thank you for reporting!
I was not able to reproduce this issue with a new profile using the latest Firefox Nightly.
Still, this issue may have been encountered if you have  `privacy.resistFingerprinting` pref in "about:config" page set to `true`. Can you please verify if this might be the reason?

**Comment by vhfmag** [comment] 2018-11-16 12:59
Yes, that was the reason, disabling `privacy.resistFingerprinting` solved it. Thanks!

Should I leave this issue open or close it?

**Comment by Softvision-RemusDranca** [comment] 2018-11-16 15:56
Looking more deep in to this, there might be a work around for this issue, if the `privacy.resistFingerprinting` is enabled:
1. Go to "about:config" page.
2. Right-click on the list of preferences, and select New > Boolean.
3. Enter `privacy.resistFingerprinting.block_mozAddonManager` as the preference name.
4. Enter `false` as the preference value.

Please let me know how this goes! Thank you!

**Comment by biancadanforth** [comment] 2018-11-16 18:08
Thank you @Softvision-RemusDranca for stepping in here. Let's leave this issue open in case it becomes a problem for all users when Nightly 65 eventually becomes Release 65. It could be similar to #183 . Either way, worth digging a little more.

**Comment by Osmose** [comment] 2018-11-16 18:16
This is a bug in Firefox: [Bug 1394448](https://bugzilla.mozilla.org/show_bug.cgi?id=1394448). The resist fingerprinting pref sets your user agent to the last Firefox ESR version, which is currently 60. It sets it in a way that add-ons get the incorrect browser version, though.

I'm going to close this as there's not much we can do on our end to fix this. Thanks for the issue!

**Closed by Osmose** 2018-11-16 18:16 UTC
Labels: [ENG]: Triage
