### ISSUE TITLE
[Linux] A blank space is displayed on the right side of the door hanger after pinning the Price Wise toolbar button in the Overflow Menu

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/price-wise#256] opened 2018-11-08 16:29 UTC
[Affected versions]:
- Firefox Release v63.0.1 and up

[Affected Platforms]:
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Price Wise" add-on (10.0.0) downloaded from ([download link](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest)). 
- The Price Wise button was pinned to the Overflow Menu.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "More tools..." toolbar button and select the "Tracked Products" option.
3. Observe the UI of the "Price Watcher List".

[Expected result]:
- The door hanger is correctly displayed, without any UI issues.

[Actual result]:
- A blank space is displayed on the right side of the door hanger.

[Notes]:
- This issue is also reproducible when there are products in the Price Wise list.
- Here is a screen recording of the issue:

![linux issue](https://user-images.githubusercontent.com/26000308/48212246-e232c880-e383-11e8-9efb-20b6ec72f762.gif)

**Comment by biancadanforth** [comment] 2018-11-12 17:18
Thanks for filing this issue.

I'm going to guess the Overflow menu on Linux is even wider than our max-width of 400px from PR #249 .

**Comment by Osmose** [comment] 2018-11-12 17:23
I've seen this on MacOS before, it went away after I closed and reopened the panel. I wonder if it has something to do with how Firefox is determining the panel width?

**Comment by SoftVision-CarmenFat** [comment] 2018-11-22 15:44
Tested this again using the latest Price Wise version (15.0.0) from Test Pilot platform on Ubuntu 18.04 x64 and the blank space is still displayed on the right side of the door hanger. Reopening the issue accordingly.

**Comment by biancadanforth** [comment] 2018-11-26 16:52
@SoftVision-CarmenFat , the fix for this landed after v15.0.0 was released, so I would not expect any changes in v15.0.0. As a result, I am going to close this issue again.

We will likely cut a new release later this week that will hopefully include this patch, but there is a way for you to check whether you can verify an issue with the [latest official release](https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest) or not:
* In this case, any commits on [`master`](https://github.com/mozilla/price-wise/commits/master) above the commit labeled `15.0.0` will not have their changes reflected in v15.0.0.

**Closed by biancadanforth** 2018-11-26 16:52 UTC
Labels: [QA]:Normal issue

**Comment by Softvision-RemusDranca** [comment] 2018-11-27 10:19
I have verified this issue using the latest Price Wise version (15.0.0) custom build and the issue is no longer reproducible. Tested on Ubuntu 18.04 x64 and Arch Linux 4.16.6 x64.
