### ISSUE TITLE
The eBay favicon is not displayed on the left side of the product's price when accessing the door hanger in Private Browsing Mode

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/price-wise#243] opened 2018-11-05 14:06 UTC
[Affected versions]:
- Firefox Release v63.0 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac (except Nightly channel)

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Price Wise" add-on (8.0.1) downloaded from ([download link](https://usercontent.irccloud-cdn.com/file/LCrGGoJF/price_wise-8.0.1-signed.xpi)). 
- A product from eBay was already added to the list.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Press "Ctrl"+"Shift"+"P" keys in order to open a Private Window.
4. Click the Price Wise toolbar button from the Private Window.
5. Observe the favicon of the website.

[Expected result]:
- The eBay favicon is displayed on the left side of the product's price.

[Actual result]:
- The eBay favicon is not displayed.

[Notes]:
- Here is a screen recording of the issue:

![pbm](https://user-images.githubusercontent.com/26000308/48002568-97f7e000-e114-11e8-8927-6b833d791592.gif)

**Comment by biancadanforth** [comment] 2018-11-19 17:59
Moving this to reserve in favor of #274 .

**Closed** 2018-11-28 23:07 UTC
Labels: [ENG]: Reserve, [QA]:Normal issue

**Comment by Softvision-RemusDranca** [comment] 2018-11-29 14:00
I have verified this issue using the latest Price Wise version (16.0.0) custom build on 11/29/2018, and the issue is no longer reproducible. Tested on Windows 10x64, Mac 10.13 and Ubuntu 18.04 x64.
