### ISSUE TITLE
Post MVP: Incorrect extraction on Amazon page with no price (requires further selection)

### ISSUE THREAD

**Issue by javaun** [mozilla/price-wise#229] opened 2018-10-30 20:40 UTC
Price Wise picked up a price of "97.00" on this page, but there is no price. (Could it be model number?)

https://www.amazon.com/gp/product/B01M0PT498/ref=s9u_wsim_gw_i3?ie=UTF8&fpl=fresh&pd_rd_i=B01M0PT498&pd_rd_r=6b833ed8-dc83-11e8-b4bb-e977208e204c&pd_rd_w=SA48L&pd_rd_wg=hgjNC&pf_rd_m=ATVPDKIKX0DER&pf_rd_s=&pf_rd_r=0S2W99XH49AA8QBA5CGX&pf_rd_t=36701&pf_rd_p=321f47e6-4a41-4f0d-a894-0c54b4c3256b&pf_rd_i=desktop

<img width="1210" alt="amazon_com__seiko_men_s__automatic_classic_dress__japanese_stainless_steel_and_leather_casual_watch__color_black__model__srpa97___watches" src="https://user-images.githubusercontent.com/126270/47749006-84ef9680-dc62-11e8-8e6c-f7229b5dc1da.png">

<img width="1127" alt="screen shot 2018-10-30 at 4 39 28 pm" src="https://user-images.githubusercontent.com/126270/47749028-90db5880-dc62-11e8-86a8-14e6b4625d15.png">

**Comment by muccimoz** [comment] 2018-10-30 21:08
Duplicate of  #86

**Closed** 2018-10-30 21:09 UTC
