### ISSUE TITLE
Adding product when on landing page causes add-on to become unuseful

### ISSUE THREAD

**Issue by poubina** [mozilla/price-wise#239] opened 2018-11-01 18:27 UTC
[Affected versions]:
    Firefox 63.0

[Affected Platforms]:
    Windows 10 (due to hardware/software restrictions bug will verified on remaining OSes on following days).

[Prerequisites]:
    Price Wise installed from https://testpilot.firefox.com/files/shopping-testpilot@mozilla.org/latest

[Steps to reproduce]:
    Open the browser and navigate to "http://www.ebay.com/" , "http://www.amazon.com/" , "http://www.bestbuy.com/" , "http://www.walmart.com/".
    Wait for landing page to fully load.
    Click on Price Wise.
    Click "Add This Product" button and observe the behavior.

[Expected result]:
    The "Add This Product" button is not actionable (we are on landing page).

[Actual result]:
    The "Add This Product" button is actionable and then add-on become unuseful. USER MUST REMOVE AND REINSTALL ADD-ON to use it again.

[Notes]:
    See screenshots attached.

![amazon landing page 2](https://user-images.githubusercontent.com/44272078/47871276-72a06480-ddea-11e8-9df3-0d6ace1a276e.png)
![ebay landing page 2](https://user-images.githubusercontent.com/44272078/47871278-72a06480-ddea-11e8-8c15-3ee0d7770b7f.png)
![ebay landing page](https://user-images.githubusercontent.com/44272078/47871279-72a06480-ddea-11e8-9506-7934df459213.png)
![amazon landing page](https://user-images.githubusercontent.com/44272078/47871280-7338fb00-ddea-11e8-875b-8a49a6e9cc02.png)
![walmart landing page](https://user-images.githubusercontent.com/44272078/47872663-f60f8500-dded-11e8-810a-090e8f57e791.png)
![bestbuy landing page](https://user-images.githubusercontent.com/44272078/47872664-f6a81b80-dded-11e8-972d-d9d36bbb9da5.png)

**Comment by biancadanforth** [comment] 2018-11-01 20:12
Thank you for taking the time to file this issue. Closing as this is a dupe of #225 .

**Closed by biancadanforth** 2018-11-01 20:12 UTC
Labels: [triage]
